version: "3.3"

services:
  web:
    build:
      context: .
    command: gunicorn dacha.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/home/user/web/static
      - ./media:/home/user/web/media
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    expose:
      - 5432

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A dacha worker -l info
    volumes:
      - .:/home/user/web/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
