# Generated by Django 3.2.7 on 2021-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='beds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estate',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='api.EstateFacility'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='people',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estate',
            name='pool',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
