# Generated by Django 3.2.8 on 2021-12-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_region_regiontranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='district',
            field=models.CharField(default='', max_length=255, verbose_name='Tuman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='region',
            field=models.CharField(default='', max_length=255, verbose_name='Viloyat'),
            preserve_default=False,
        ),
    ]
