# Generated by Django 3.2.7 on 2021-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211005_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('expires_in', models.DateTimeField()),
            ],
        ),
    ]
