# Generated by Django 3.2.8 on 2021-12-21 11:51

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211221_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.region')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='estate',
            name='district',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='region',
        ),
        migrations.AddField(
            model_name='estatetranslation',
            name='district',
            field=models.CharField(default='', max_length=255, verbose_name='Tuman'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estatetranslation',
            name='region',
            field=models.CharField(default='', max_length=255, verbose_name='Viloyat'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DistrictTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.district')),
            ],
            options={
                'verbose_name': 'district Translation',
                'db_table': 'api_district_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
