# Generated by Django 3.2.7 on 2021-10-08 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_smscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='smscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
