# Generated by Django 3.2.8 on 2021-12-22 21:14

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_estate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
