# Generated by Django 3.2.8 on 2021-12-22 21:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_estate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=20, size=[500, 300], upload_to=''),
        ),
    ]
