# Generated by Django 3.2.7 on 2021-10-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211015_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatefacility',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
