# Generated by Django 3.2.7 on 2021-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_estatefacility_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatefacility',
            name='slug',
        ),
        migrations.AddField(
            model_name='estatetype',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
