# Generated by Django 3.2.7 on 2021-10-18 18:35

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211015_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_days', to='api.estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, api.models.DateTimeMixin),
        ),
    ]
