# Generated by Django 3.2.8 on 2022-01-14 10:25

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
            bases=(models.Model, api.models.DateTimeMixin),
        ),
        migrations.AlterField(
            model_name='estatephoto',
            name='estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.estate'),
        ),
    ]
