# Generated by Django 3.2.7 on 2021-10-18 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_estatebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, django.db.models.fields.DateTimeField),
        ),
    ]
