# Generated by Django 3.2.7 on 2021-10-18 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_estaterating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.estate')),
            ],
            bases=(models.Model, django.db.models.fields.DateTimeField),
        ),
    ]
