# Generated by Django 3.2.7 on 2021-10-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_estateviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_top',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
