# Generated by Django 3.2.8 on 2022-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220118_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingplan',
            name='limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertisingplan',
            name='limit_count',
            field=models.IntegerField(default=0),
        ),
    ]
