# Generated by Django 3.2.7 on 2021-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_estate_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='description',
        ),
        migrations.AddField(
            model_name='estatetranslation',
            name='description',
            field=models.TextField(default='', verbose_name='Tavsif'),
            preserve_default=False,
        ),
    ]
