# Generated by Django 3.2.8 on 2022-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220118_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(default='d.png', upload_to='user/'),
        ),
    ]
