# Generated by Django 3.2.7 on 2021-10-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211025_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='district',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='region',
        ),
        migrations.AddField(
            model_name='estate',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Manzil'),
            preserve_default=False,
        ),
    ]
