# Generated by Django 3.2.8 on 2022-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatefacility',
            name='category',
            field=models.ManyToManyField(to='api.EstateType'),
        ),
    ]
