# Generated by Django 3.2.8 on 2022-02-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_estatefacility_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatefacility',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
