# Generated by Django 3.2.7 on 2021-10-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211025_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='expires_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
