# Generated by Django 3.2.8 on 2022-02-16 03:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_estatefacility_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=80, size=[500, 300], upload_to='images'),
        ),
    ]
