# Generated by Django 3.2.8 on 2022-02-16 03:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_estate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=80, size=[750, 450], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='estatephoto',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=80, size=[750, 450], upload_to='images'),
        ),
    ]
