# Generated by Django 3.2.8 on 2022-03-12 03:27

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220228_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, null=True, quality=100, size=[300, 180], upload_to='images'),
        ),
        migrations.CreateModel(
            name='ServiceItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.serviceitem')),
            ],
            options={
                'verbose_name': 'service item Translation',
                'db_table': 'api_serviceitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
