# Generated by Django 3.2.8 on 2022-03-12 05:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220312_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, null=True, quality=70, size=[200, 120], upload_to='images'),
        ),
    ]
