# Generated by Django 3.2.8 on 2022-03-14 02:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_estate_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpg', keep_meta=True, quality=100, size=[1500, 900], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpg', keep_meta=True, null=True, quality=70, size=[200, 120], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='estatephoto',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpg', keep_meta=True, quality=100, size=[1500, 900], upload_to='images'),
        ),
    ]
