# Generated by Django 3.2.8 on 2022-03-14 02:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220314_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=True, null=True, quality=80, size=[300, 180], upload_to='images'),
        ),
    ]
