# Generated by Django 3.2.8 on 2022-03-14 02:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_estate_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=False, quality=100, size=[4500, 2700], upload_to='images'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=False, null=True, quality=100, size=[300, 180], upload_to='images'),
        ),
    ]
