# Generated by Django 3.2.8 on 2022-03-14 02:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_estate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=False, null=True, quality=100, size=[500, 300], upload_to='images'),
        ),
    ]
