# Generated by Django 3.2.8 on 2022-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_estate_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisingplan',
            options={'verbose_name': 'Reklama turlari'},
        ),
        migrations.AlterModelOptions(
            name='advertisingplantranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Reklama turlari Translation'},
        ),
        migrations.AlterModelOptions(
            name='balancecharge',
            options={'verbose_name': "O'tkazmalar"},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Pul birliklari'},
        ),
        migrations.AlterModelOptions(
            name='currencytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Pul birliklari Translation'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='districttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Tumanlar Translation'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': "E'lonlar"},
        ),
        migrations.AlterModelOptions(
            name='estatebanner',
            options={'verbose_name': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='estatefacility',
            options={'verbose_name': 'Qulayliklar'},
        ),
        migrations.AlterModelOptions(
            name='estatefacilitytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Qulayliklar Translation'},
        ),
        migrations.AlterModelOptions(
            name='estatephoto',
            options={'verbose_name': "Qo'shimcha rasmlar"},
        ),
        migrations.AlterModelOptions(
            name='estatetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': "E'lonlar Translation"},
        ),
        migrations.AlterModelOptions(
            name='estatetype',
            options={'verbose_name': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='estatetypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Kategoriyalar Translation'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='popularplace',
            options={'verbose_name': 'Mashxur joylar'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='regiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Viloyatlar Translation'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmat turlar'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='serviceitemtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Xizmatlar Translation'},
        ),
        migrations.AlterModelOptions(
            name='servicetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Xizmat turlar Translation'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Statik sahifalar'},
        ),
        migrations.AlterModelOptions(
            name='staticpagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Statik sahifalar Translation'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='estatefacility',
            name='category',
            field=models.ManyToManyField(related_name='Kategoriya', to='api.EstateType'),
        ),
        migrations.AlterField(
            model_name='estatefacility',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Qisqacha nom'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='background_color',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Orqa foni'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='foreground_color',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Rangi'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Mavqeyi'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha nom'),
        ),
    ]
