# Generated by Django 3.2.9 on 2022-04-04 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220326_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisingplan',
            options={'verbose_name': 'Тип рекламы', 'verbose_name_plural': 'Типы рекламы'},
        ),
        migrations.AlterModelOptions(
            name='advertisingplantranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Тип рекламы Translation'},
        ),
        migrations.AlterModelOptions(
            name='balancecharge',
            options={'verbose_name': 'Трансфер', 'verbose_name_plural': 'Трансферы'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='currencytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Валюта Translation'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='districttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Район Translation'},
        ),
        migrations.AlterModelOptions(
            name='estate',
            options={'verbose_name': 'Объявления', 'verbose_name_plural': 'Объявленияи'},
        ),
        migrations.AlterModelOptions(
            name='estatebanner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='estatefacility',
            options={'verbose_name': 'Удобство', 'verbose_name_plural': 'Удобства'},
        ),
        migrations.AlterModelOptions(
            name='estatefacilitytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Удобство Translation'},
        ),
        migrations.AlterModelOptions(
            name='estatephoto',
            options={'verbose_name': 'Дополнительное изображение', 'verbose_name_plural': 'Дополнительные изображения'},
        ),
        migrations.AlterModelOptions(
            name='estatetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Объявления Translation'},
        ),
        migrations.AlterModelOptions(
            name='estatetype',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='estatetypetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Категория Translation'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='popularplace',
            options={'verbose_name': 'Известное место', 'verbose_name_plural': 'Знаменитые места'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='regiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Область Translation'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Тип сервиса', 'verbose_name_plural': 'Типы сервиса'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceitemtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Услуга Translation'},
        ),
        migrations.AlterModelOptions(
            name='servicetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Тип сервиса Translation'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Статическая страница', 'verbose_name_plural': 'Статические страницы'},
        ),
        migrations.AlterModelOptions(
            name='staticpagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Статическая страница Translation'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisingplan',
            name='days',
            field=models.IntegerField(verbose_name='Дни'),
        ),
        migrations.AlterField(
            model_name='advertisingplan',
            name='limit',
            field=models.BooleanField(default=False, verbose_name='Ограничение'),
        ),
        migrations.AlterField(
            model_name='advertisingplan',
            name='limit_count',
            field=models.IntegerField(default=0, verbose_name='Количество ограничений'),
        ),
        migrations.AlterField(
            model_name='advertisingplan',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisingplan',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Слизняк'),
        ),
        migrations.AlterField(
            model_name='advertisingplantranslation',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='advertisingplantranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='balancecharge',
            name='amount',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='balancecharge',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершенный?'),
        ),
        migrations.AlterField(
            model_name='balancecharge',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='balancecharge',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='balancecharge',
            name='type',
            field=models.CharField(choices=[('in', 'Доход'), ('out', 'Расходы')], max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='currencytranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='districttranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='announcer',
            field=models.CharField(max_length=255, verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='beds',
            field=models.IntegerField(blank=True, default=5, verbose_name='Количество кроватей'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='estate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estatetype', verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='expires_in',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='api.EstateFacility', verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_ads',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Реклама'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_banner',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Это напечатано?'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_simple',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Простое объявление'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_top',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ТОП объявление'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_topbanner',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Топ баннер'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='latitute',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='longtitute',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='people',
            field=models.IntegerField(blank=True, default=5, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=False, quality=100, size=[3000, 1800], upload_to='images', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='pool',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество бассейнов'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='popular_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.popularplace', verbose_name='Знаменитое место'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.currency', verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='jpeg', keep_meta=False, null=True, quality=100, size=[500, 300], upload_to='images', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль рекламодателя'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='weekday_price',
            field=models.FloatField(verbose_name='Цены в будние дни'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='weekend_price',
            field=models.FloatField(verbose_name='Цены выходного дня'),
        ),
        migrations.AlterField(
            model_name='estatebooking',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_days', to='api.estate', verbose_name='Объявления'),
        ),
        migrations.AlterField(
            model_name='estatebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='estatefacility',
            name='category',
            field=models.ManyToManyField(related_name='facilities', to='api.EstateType'),
        ),
        migrations.AlterField(
            model_name='estatefacility',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Короткое имя'),
        ),
        migrations.AlterField(
            model_name='estatefacilitytranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='estatetranslation',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='estatetranslation',
            name='district',
            field=models.CharField(max_length=255, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='estatetranslation',
            name='region',
            field=models.CharField(max_length=255, verbose_name='Провинция'),
        ),
        migrations.AlterField(
            model_name='estatetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='background_color',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Фоновый цвет'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='foreground_color',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='estatetype',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое имя'),
        ),
        migrations.AlterField(
            model_name='estatetypetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Обратная связь'),
        ),
        migrations.AlterField(
            model_name='popularplace',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Эл. адрес'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Слизняк'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service', verbose_name='Типы сервиса'),
        ),
        migrations.AlterField(
            model_name='serviceitemtranslation',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpagetranslation',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='staticpagetranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=25, unique=True, verbose_name='Телефонный номер'),
        ),
    ]
