# Generated by Django 3.2.9 on 2022-04-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_user_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thumbnail',
        ),
    ]
