JAZZMIN_SETTINGS = {
    "site_title": "DachaTurizm",
    "site_header": "DachaTurizm",
    "site_brand": "DachaTurizm",
    "site_icon": None,
    "welcome_sign": "DachaTurizm ga xush kelibsiz!",
    "copyright": "DachaTurizm MCHJ",
    "search_model": "api.User",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "api.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}